pipeline:
  build:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=./.gradle
    commands:
      - ./gradlew build
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
      - exit 1
  test:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=./.gradle
    when:
      status: success
    commands:
      - ./gradlew test
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
      - exit 1
  jar:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=./.gradle
    commands:
      - ./gradlew fatJar
    when:
      branch: master
      status: success
  docker:
    when:
      branch: master
      status: success
    image: plugins/docker:1.12
    repo: build.registry.eorlbruder.de/bookmarksync
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: ./
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD
  notify:
    image: drillster/drone-email
    when:
      branch: master
      status: [failure, changed, success]
    host: $DRONE_SMTP
    username: $DRONE_ADMIN_MAIL
    from: $DRONE_ADMIN_MAIL
    recipients:
     - $DRONE_ADMIN_MAIL
    password: $DRONE_ADMIN_MAIL_PW
    commands:
      - echo $DRONE_ADMIN_MAIL
