pipeline:
  test:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/.gradle
    commands:
      - ./gradlew test
  build:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/.gradle
    commands:
      - ./gradlew fatJar
      - ls
    when:
      branch: master
      status: [ sucess ]
  notify:
    image: drillster/drone-email
    when:
      status: [ changed, failure ]
    host: ${DRONE_SMTP}
    username: $DRONE_ADMIN_MAIL
    from: $DRONE_ADMIN_MAIL
    recipients:
     - $DRONE_ADMIN_MAIL
    password: $DRONE_ADMIN_MAIL_PW
