pipeline:
  test:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/.gradle
    commands:
      - ./gradlew test
  build:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=/.gradle
    commands:
      - ./gradlew jar
      - ls
  notify:
    image: drillster/drone-email
    when:
      status: [ changed, failure ]
    secrets:
      host: drone_smtp
      username: drone_admin_mail
      from: drone_admin_mail
      recipients:
       - drone_admin_mail
      password: drone_admin_mail_pw
